name: tests

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
                mongodb-version: ["6.0"]

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.8.0
              with:
                  mongodb-version: ${{ matrix.mongodb-version }}

            - run: npm install

            - run: npm test
